// dificuldades Facil:0 Medio:1 Dificil:2


const ListaDePalavras = [
    //animais
    [
        [
        { palavra: 'CACHORRO', dica: 'Melhor amigo do homem'},
        { palavra: 'GATO', dica: 'Animal que gosta de dormir e ronronar' },
        { palavra: 'PÁSSARO', dica: 'Animal que voa e canta' },
        { palavra: 'PEIXE', dica: 'Animal que nada na água' },
        { palavra: 'ELEFANTE', dica: 'O maior animal terrestre com tromba' },
        { palavra: 'LEÃO', dica: 'Conhecido como rei da selva' },
        { palavra: 'CAVALO', dica: 'Animal usado para montar e correr' },
        { palavra: 'COELHO', dica: 'Animal que pula e tem orelhas longas' },
        { palavra: 'VACA', dica: 'Animal que dá leite' },
        { palavra: 'PORCO', dica: 'Animal que gosta de lama' },
        { palavra: 'URSO', dica: 'Animal grande que gosta de mel' },
        { palavra: 'MACACO', dica: 'Animal que gosta de bananas e sobe em árvores' },
        { palavra: 'TARTARUGA', dica: 'Animal com casco duro que anda devagar' },
        { palavra: 'GALINHA', dica: 'Animal que bota ovos' },
        { palavra: 'PATO', dica: 'Animal que nada e grasna' },
        { palavra: 'COBRA', dica: 'Animal que não tem patas e pode ser venenoso' },
        { palavra: 'GALO', dica: 'Animal que canta de manhã' },
        { palavra: 'RATO', dica: 'Animal pequeno que gosta de queijo' },
        { palavra: 'CAMELO', dica: 'Animal do deserto com corcova' },
        { palavra: 'ZEBRA', dica: 'Animal parecido com cavalo, com listras pretas e brancas' },
        { palavra: 'PINGUIM', dica: 'Pássaro que não voa e vive no frio' },
        { palavra: 'CORUJA', dica: 'Ave que é símbolo da sabedoria' },
        { palavra: 'TIGRE', dica: 'Felino listrado de laranja e preto' },
        { palavra: 'COALA', dica: 'Animal que gosta de comer folhas de eucalipto' },
        { palavra: 'GIRAFAS', dica: 'Animal com pescoço muito comprido' },
        { palavra: 'PAPAGAIO', dica: 'Pássaro que pode falar' },
        { palavra: 'ABELHA', dica: 'Inseto que produz mel' },
        { palavra: 'FORMIGA', dica: 'Inseto que vive em colônias' },
        { palavra: 'CACHALOTE', dica: 'Grande mamífero marinho' },
        { palavra: 'GOLFINHO', dica: 'Mamífero marinho inteligente e brincalhão' },
        { palavra: 'PAVÃO', dica: 'Ave com cauda colorida e vistosa' },
        { palavra: 'GANSO', dica: 'Ave parecida com o pato, mas maior' },
        { palavra: 'CROCODILO', dica: 'Réptil grande que vive em rios' },
        { palavra: 'JACARÉ', dica: 'Réptil parecido com crocodilo, mas com focinho mais curto' },
        { palavra: 'CARANGUEJO', dica: 'Crustáceo que anda para os lados' },
        { palavra: 'LAGARTIXA', dica: 'Pequeno réptil que pode escalar paredes' },
        { palavra: 'MORCEGO', dica: 'Único mamífero que voa' },
        { palavra: 'CORAL', dica: 'Animal marinho que forma recifes' },
        { palavra: 'ESTRELA', dica: 'Animal marinho com braços em forma de estrela' },
        { palavra: 'GAMBA', dica: 'Animal marinho semelhante a camarão' },
        { palavra: 'ARARA', dica: 'Pássaro colorido que vive na floresta amazônica' },
        { palavra: 'ONÇA', dica: 'Grande felino da América do Sul' },
        { palavra: 'BÚFALO', dica: 'Animal grande que vive em manadas' },
        { palavra: 'CANGURU', dica: 'Animal que pula e tem bolsa para filhote' },
        { palavra: 'LEOPARDO', dica: 'Felino com manchas no corpo' },
        { palavra: 'PANTERA', dica: 'Felino escuro e ágil' },
        ],
        [
            
            { palavra: 'BEM-TE-VI', dica: 'Pássaro que anuncia a chegada do dia' },
            { palavra: 'TAMANDUÁ', dica: 'Animal que come formigas e tem língua comprida' },
            { palavra: 'CUTIA', dica: 'Roedor da Mata Atlântica' },
            { palavra: 'JIBOIA', dica: 'Grande serpente não venenosa' },
            { palavra: 'MICO-LEÃO', dica: 'Macaco pequeno com pelagem dourada' },
            { palavra: 'QUATI', dica: 'Animal parecido com guaxinim' },
            { palavra: 'GAVIÃO', dica: 'Ave de rapina comum no Brasil' },
            { palavra: 'TATU', dica: 'Animal com carapaça que se enrola' },
            { palavra: 'PEIXE-BOI', dica: 'Mamífero marinho herbívoro' },
            { palavra: 'PACA', dica: 'Roedor grande da América do Sul' },
            { palavra: 'ANACONDA', dica: 'Serpente grande e pesada da Amazônia' },
            { palavra: 'BICHO-PREGUIÇA', dica: 'Animal que se move lentamente nas árvores' },
            { palavra: 'CACHORRO-DO-MATO', dica: 'Canídeo selvagem brasileiro' },
            { palavra: 'RAPOSA', dica: 'Animal parecido com um pequeno cão selvagem' },
            { palavra: 'JAGUATIRICA', dica: 'Felino selvagem com manchas' },
            { palavra: 'GARÇA', dica: 'Ave de pescoço comprido que vive perto da água' },
            { palavra: 'CORUJA', dica: 'Ave noturna símbolo da sabedoria' },
            { palavra: 'CISNE', dica: 'Ave branca elegante que nada' },
            { palavra: 'TUCANO', dica: 'Ave com bico grande e colorido' },
            { palavra: 'CAPIVARA', dica: 'O maior roedor do mundo' },
            { palavra: 'PACA', dica: 'Roedor sul-americano com manchas' },
            { palavra: 'FURÃO', dica: 'Pequeno mamífero doméstico' },
            { palavra: 'ANDORINHA', dica: 'Ave migratória que constrói ninhos de barro' },
            { palavra: 'JABUTI', dica: 'Tartaruga terrestre' },
            { palavra: 'GUAXINIM', dica: 'Mamífero com máscara preta no rosto' },
            { palavra: 'MARRECO', dica: 'Pato pequeno' },
            { palavra: 'ONÇA-PINTADA', dica: 'Grande felino com manchas negras' },
            { palavra: 'PAVÃO', dica: 'Ave com cauda colorida' },
            { palavra: 'GAMBA', dica: 'Animal marinho semelhante a camarão' },
            { palavra: 'CACHALOTE', dica: 'Grande baleia dentada' },
            { palavra: 'GARÇA', dica: 'Ave de pescoço longo que caça peixes' },
            { palavra: 'JIBÓIA', dica: 'Serpente grande não venenosa' },
            { palavra: 'LONTRA', dica: 'Mamífero aquático' },
            { palavra: 'CANGURU', dica: 'Marsupial que pula' },
            { palavra: 'PAPAGAIO', dica: 'Ave que imita sons' },
            { palavra: 'TAMANDUÁ', dica: 'Come formigas e cupins' },
            { palavra: 'TUCANO', dica: 'Ave com bico grande e colorido' },
            { palavra: 'GANSO', dica: 'Ave parecida com pato, mas maior' },
            { palavra: 'PEIXE-BOI', dica: 'Mamífero marinho herbívoro' },
            { palavra: 'CAVALO', dica: 'Animal usado para montar' }
        ],
        [
        { palavra: 'AXOLOTE', dica: 'Sapo mexicano que mantém características larvais na vida adulta' },
        { palavra: 'NARVAL', dica: 'Baleia com um longo "chifre" na cabeça' },
        { palavra: 'OKAPI', dica: 'Parente da girafa com corpo parecido com zebra' },
        { palavra: 'TAPIR', dica: 'Mamífero com focinho alongado, parecido com um porco grande' },
        { palavra: 'PANGOLIM', dica: 'Mamífero coberto por escamas' },
        { palavra: 'MURICUCA', dica: 'Peixe típico da Amazônia' },
        { palavra: 'GALOCA', dica: 'Palavra desconhecida, substituirei' },
        { palavra: 'MIRIMIRI', dica: 'Palavra indígena, substituirei' },
        { palavra: 'URUTAU', dica: 'Ave noturna da América do Sul' },
        { palavra: 'BICHOPREGUIÇA', dica: 'Animal que se move lentamente' },
        { palavra: 'QUIRIRI', dica: 'Palavra indígena para um pássaro' },
        { palavra: 'JACU', dica: 'Ave típica da Mata Atlântica' },
        { palavra: 'GAMBÁ', dica: 'Mamífero que exala mau cheiro para se defender' },
        { palavra: 'JAGUATIRICA', dica: 'Felino selvagem com manchas' },
        { palavra: 'JAGUAR', dica: 'Grande felino da América do Sul' },
        { palavra: 'CUXIÚ', dica: 'Ave da Amazônia' },
        { palavra: 'TAMANDUÁ', dica: 'Come formigas e cupins' },
        { palavra: 'ARARA', dica: 'Ave colorida da Amazônia' },
        { palavra: 'PEIXEBOI', dica: 'Mamífero marinho herbívoro' },
        { palavra: 'ONÇAPINTADA', dica: 'Grande felino manchado' },
        { palavra: 'LAGARTIXA', dica: 'Pequeno réptil que pode escalar paredes' },
        { palavra: 'CASCUDO', dica: 'Peixe de água doce com armadura' },
        { palavra: 'GAMBA', dica: 'Crustáceo semelhante a camarão' },
        { palavra: 'TUCAN', dica: 'Ave com bico grande e colorido' },
        { palavra: 'ARARA', dica: 'Ave amazônica colorida' },
        { palavra: 'MICOLEÃO', dica: 'Pequeno macaco dourado' },
        { palavra: 'PANTERA', dica: 'Felino escuro e ágil' },
        { palavra: 'CANGURU', dica: 'Marsupial que pula' },
        { palavra: 'GAMBÁ', dica: 'Mamífero que exala mau cheiro' },
        { palavra: 'LOBO', dica: 'Parente selvagem do cão' },
        { palavra: 'ONÇA', dica: 'Felino selvagem da América do Sul' },
        { palavra: 'LONTRA', dica: 'Mamífero aquático' },
        { palavra: 'ARARANHA', dica: 'Ave vermelha da Amazônia' },
        { palavra: 'GAVIÃO', dica: 'Ave de rapina' },
        { palavra: 'BÚFALO', dica: 'Animal grande que vive em manadas' },
        { palavra: 'JABUTI', dica: 'Tartaruga terrestre' },
        { palavra: 'GUAXINIM', dica: 'Mamífero com máscara preta no rosto' },
        { palavra: 'MURICUCA', dica: 'Peixe amazônico' },
        { palavra: 'TATU', dica: 'Animal com carapaça' },
        { palavra: 'CORUJA', dica: 'Ave noturna' },
        { palavra: 'JIBÓIA', dica: 'Serpente grande' },
        { palavra: 'PAVÃO', dica: 'Ave com cauda colorida' },
        { palavra: 'GAMBA', dica: 'Crustáceo semelhante a camarão' },
        { palavra: 'JACU', dica: 'Ave que habita a Mata Atlântica' },
        { palavra: 'ARARANHA', dica: 'Grande ave vermelha da Amazônia' }
        
        ]
    ],
    // heróis
    [
        [ // Nível fácil
        { palavra: 'Superman', dica: 'Voa, tem visão de raio-X e é vulnerável à kriptonita'},
        { palavra: 'Batman', dica: 'Herói de capa negra e cinto de utilidades' },
        { palavra: 'Homem-Aranha', dica: 'Solta teias e escala paredes' },
        { palavra: 'Mulher-Maravilha', dica: 'Princesa amazona com laço da verdade' },
        { palavra: 'Homem de Ferro', dica: 'Gênio bilionário em uma armadura tecnológica' },
        { palavra: 'Capitão América', dica: 'Herói patriota com escudo indestrutível' },
        { palavra: 'Thor', dica: 'Deus do trovão que empunha o martelo Mjölnir' },
        { palavra: 'Hulk', dica: 'Fica verde e superforte quando se irrita' },
        { palavra: 'Flash', dica: 'Velocista escarlate que quebra a barreira do som' },
        { palavra: 'Wolverine', dica: 'Mutante com garras de adamantium e fator de cura' },
        { palavra: 'Viúva Negra', dica: 'Espiã russa dos Vingadores' },
        { palavra: 'Gavião Arqueiro', dica: 'Mestre do arco e flecha da S.H.I.E.L.D.' },
        { palavra: 'Homem-Formiga', dica: 'Pode encolher e se comunicar com insetos' },
        { palavra: 'Pantera Negra', dica: 'Rei de Wakanda com traje de vibranium' },
        { palavra: 'Capitã Marvel', dica: 'Heroína poderosa com energia cósmica' }, 
        { palavra: 'Robin', dica: 'Parceiro do Batman' }
        ],
        [ // Nível Medio
        { palavra: 'Shazam', dica: 'Garoto que vira herói ao dizer uma palavra mágica' },
        { palavra: 'Aquaman', dica: 'Rei de Atlântida que comanda os oceanos' },
        { palavra: 'Ciclope', dica: 'Mutante que dispara raios pelos olhos' },
        { palavra: 'Feiticeira Escarlate', dica: 'Controla a realidade com magia do caos' },
        { palavra: 'Visão', dica: 'Androide com joia da mente' },
        { palavra: 'Doutor Estranho', dica: 'Mago supremo do universo Marvel' },
        { palavra: 'Motoqueiro Fantasma', dica: 'Espírito da vingança com moto flamejante' },
        { palavra: 'Demolidor', dica: 'Herói cego com sentidos aguçados' },
        { palavra: 'Luke Cage', dica: 'Homem com pele invulnerável' },
        { palavra: 'Jessica Jones', dica: 'Detetive com superforça' },
        { palavra: 'Ravena', dica: 'Filha de um demônio com poderes sombrios' },
        { palavra: 'Estelar', dica: 'Princesa alienígena com poderes de energia' },
        { palavra: 'Noturno', dica: 'Mutante que se teletransporta' },
        { palavra: 'Fera', dica: 'Mutante azul com intelecto brilhante' }
        ],
        [ // Nível difícil
        { palavra: 'Zatanna', dica: 'Feiticeira da DC que conjura feitiços falando ao contrário' },
        { palavra: 'Senhor Destino', dica: 'Mago com elmo do destino' },
        { palavra: 'Cavaleiro da Lua', dica: 'Vigilante com múltiplas personalidades e ligação com deuses egípcios' },
        { palavra: 'Senhor Milagre', dica: 'Mestre da fuga dos Novos Deuses' },
        { palavra: 'Besouro Azul', dica: 'Herói com escaravelho alienígena' },
        { palavra: 'Gladiador Dourado', dica: 'Herói do futuro que busca fama no presente' },
        { palavra: 'Espectro', dica: 'Espírito da vingança da DC' },
        { palavra: 'Lupina', dica: 'Mutante que se transforma em loba' },
        { palavra: 'Magia', dica: 'Mutante com espada mística e portais dimensionais' },
        { palavra: 'Sentinela', dica: 'Herói com poder equivalente ao de mil sóis' },
        { palavra: 'Nova', dica: 'Herói espacial com poderes cósmicos' },
        { palavra: 'Sombra', dica: 'Vilão/herói que manipula sombras' },
        { palavra: 'Vigia', dica: 'Ser que observa todos os eventos do multiverso' },
        { palavra: 'Senhor Meia-Noite', dica: 'Médico cego que combate o crime à noite' },
        { palavra: 'Fantasma', dica: 'O espírito que anda, herói pulp clássico' }
        ]
    ],
    //viloes
    [
     [ // Nível fácil
    { palavra: 'Coringa', dica: 'Palhaço do crime e maior inimigo do Batman' },
    { palavra: 'Lex Luthor', dica: 'Bilionário careca e arqui-inimigo do Superman' },
    { palavra: 'Thanos', dica: 'Titã louco que reuniu as Joias do Infinito' },
    { palavra: 'Duende Verde', dica: 'Vilão do Homem-Aranha com planador e bombas' },
    { palavra: 'Venom', dica: 'Simbionte alienígena que já foi aliado e inimigo do Homem-Aranha' },
    { palavra: 'Ultron', dica: 'Inteligência artificial criada por Tony Stark' },
    { palavra: 'Hela', dica: 'Deusa da morte e irmã de Thor' },
    { palavra: 'Loki', dica: 'Deus da trapaça e irmão adotivo de Thor' },
    { palavra: 'Magneto', dica: 'Mutante que controla o magnetismo e lidera os mutantes contra os humanos' },
    { palavra: 'Charada', dica: 'Vilão do Batman que adora enigmas' },
    { palavra: 'Pinguim', dica: 'Vilão gorducho e mafioso de Gotham' },
    { palavra: 'Arlequina', dica: 'Ex-psiquiatra e parceira do Coringa' },
    { palavra: 'Abominável', dica: 'Monstro inimigo do Hulk' },
    { palavra: 'Mysterio', dica: 'Mestre das ilusões e inimigo do Homem-Aranha' },
    { palavra: 'Apocalipse', dica: 'Antigo mutante que acredita na sobrevivência do mais forte' }
        ],
        [ // Nível intermediário
    { palavra: 'Doutor Destino', dica: 'Vilão da Marvel com armadura e magia' },
    { palavra: 'Caveira Vermelha', dica: 'Nazista inimigo do Capitão América' },
    { palavra: 'Capuz Vermelho', dica: 'Identidade de Jason Todd após sua ressurreição' },
    { palavra: 'Gorila Grodd', dica: 'Gorila superinteligente inimigo do Flash' },
    { palavra: 'Electro', dica: 'Vilão elétrico do Homem-Aranha' },
    { palavra: 'Doutor Octopus', dica: 'Cientista com braços mecânicos' },
    { palavra: 'Treinador', dica: 'Mímico de movimentos e vilão de vários heróis' },
    { palavra: 'Giganta', dica: 'Vilã com poder de crescer gigantescamente' },
    { palavra: 'Mandarim', dica: 'Vilão do Homem de Ferro com anéis mágicos' },
    { palavra: 'Homem-Areia', dica: 'Vilão que se transforma em areia' },
    { palavra: 'Encantor', dica: 'Feiticeira asgardiana rival de Thor' },
    { palavra: 'Bane', dica: 'Vilão que quebrou o Batman com força bruta e inteligência' },
        ],
        [ // Nível difícil
    { palavra: 'Kang o Conquistador', dica: 'Viajante do tempo que quer dominar todas as eras' },
    { palavra: 'Antimonitor', dica: 'Ser cósmico que destrói universos' },
    { palavra: 'Mefisto', dica: 'Demônio manipulador do universo Marvel' },
    { palavra: 'Dormammu', dica: 'Entidade sombria inimiga do Doutor Estranho' },
    { palavra: 'Trigon', dica: 'Demônio pai da Ravena' },
    { palavra: 'Neron', dica: 'Demônio que oferece pactos em troca de almas' },
    { palavra: 'Parallax', dica: 'Entidade do medo que já controlou Hal Jordan' },
    { palavra: 'Brainiac', dica: 'Alienígena colecionador de cidades e conhecimento' },
    { palavra: 'Galactus', dica: 'Devorador de mundos da Marvel' },
    { palavra: 'Dentes de Sabre', dica: 'Rival selvagem de Wolverine' },
    { palavra: 'Senhor Sinistro', dica: 'Geneticista obcecado por mutantes' },
    { palavra: 'Coração Negro', dica: 'Filho de Mefisto, criado das trevas' },
    { palavra: 'Prometeus', dica: 'Vilão da DC que derrotou a Liga da Justiça com estratégia' },
    { palavra: 'Anarquia', dica: 'Vilão filosófico que desafia a ordem social em Gotham' }
        ]
    ],
    // comidas
    [
        [ // Nível fácil
            { palavra: 'Pizza', dica: 'Comida redonda, coberta com queijo e molho de tomate' },
            { palavra: 'Hambúrguer', dica: 'Sanduíche com carne, pão, alface, queijo e outros' },
            { palavra: 'Arroz', dica: 'Grão branco muito comum no almoço' },
            { palavra: 'Batata Frita', dica: 'Tirada da raiz e servida crocante e salgada' },
            { palavra: 'Macarrão', dica: 'Massa cozida, muitas vezes com molho de tomate' },
            { palavra: 'Sorvete', dica: 'Doce gelado de vários sabores' },
            { palavra: 'Cuscuz', dica: 'Prato de milho cozido, típico do Nordeste' },
            { palavra: 'Frango', dica: 'Carne branca muito comum no prato brasileiro' },
            { palavra: 'Feijão', dica: 'Grão marrom ou preto que vai bem com arroz' },
            { palavra: 'Brigadeiro', dica: 'Doce típico brasileiro feito com chocolate e leite condensado'},
            { palavra: 'Bolo', dica: 'Doce de aniversário feito com massa assada' },
            { palavra: 'Salgadinho', dica: 'Comida pequena servida em festas, como coxinha e pastel' }
        ],
        [ // Nível intermediário
            { palavra: 'Lasanha', dica: 'Massa em camadas com carne e molho' },
            { palavra: 'Panqueca', dica: 'Massa enrolada com recheio doce ou salgado' },
            { palavra: 'Moqueca', dica: 'Prato típico com peixe e leite de coco' },
            { palavra: 'Yakissoba', dica: 'Macarrão oriental com legumes e carne' },
            { palavra: 'Churrasco', dica: 'Carne assada na brasa, muito comum em festas' },
            { palavra: 'Empadão', dica: 'Torta salgada recheada com frango ou camarão' },
            { palavra: 'Strogonoff', dica: 'Prato com carne e creme de leite, servido com arroz' },
            { palavra: 'Esfiha', dica: 'Massa recheada, típica da culinária árabe' },
            { palavra: 'Pão de Queijo', dica: 'Bolinhas feitas com polvilho e queijo' },
            { palavra: 'Sushi' , dica: ' Prato oriental de salmão e arroz enrolado na alga'},
        ],
        [ // Nível difícil
            { palavra: 'Ratatouille', dica: 'Prato francês feito com legumes cozidos' },
            { palavra: 'Quiche Lorraine', dica: 'Torta salgada francesa com ovos e bacon' },
            { palavra: 'Bobó de Camarão', dica: 'Prato baiano com camarão e creme de mandioca' },
            { palavra: 'Tartar de Salmão', dica: 'Prato cru feito com peixe picado e temperado' },
            { palavra: 'Risoto de Cogumelos', dica: 'Arroz cremoso com cogumelos' },
            { palavra: 'Goulash', dica: 'Ensopado de carne típico da Hungria' },
            { palavra: 'Paella', dica: 'Prato espanhol com arroz, frutos do mar e açafrão' },
            { palavra: 'Carpaccio', dica: 'Fatias cruas e finas de carne com molho' },
            { palavra: 'Ceviche', dica: 'Peixe cru marinado no limão, típico do Peru' },
            { palavra: 'Feijoada', dica: 'Prato brasileiro com feijão preto e carnes diversas' }
        ]
    ],
    // jogos
    [
        [ // Nível fácil
            { palavra: 'Minecraft', dica: 'Jogo de blocos e construção em mundo aberto' },
            { palavra: 'Fortnite', dica: 'Jogo de tiro com construção e batalhas online' },
            { palavra: 'Free Fire', dica: 'Jogo de tiro para celular, muito popular no Brasil' },
            { palavra: 'FIFA', dica: 'Jogo de futebol com times reais' },
            { palavra: 'Mario', dica: 'Encanador famoso que pula em inimigos' },
            { palavra: 'Sonic', dica: 'Ouriço azul super veloz' },
            { palavra: 'Subway Surfers', dica: 'Jogo de corrida infinita nos trilhos do metrô' },
            { palavra: 'Roblox', dica: 'Plataforma com milhares de jogos criados por usuários' },
            { palavra: 'The Sims', dica: 'Jogo de simulação de vida' },
            { palavra: 'Pac-Man', dica: 'Come pontos e foge de fantasmas' }
        ],
        [ // Nível intermediário
            { palavra: 'Zelda', dica: 'Jogo de aventura com espadas e quebra-cabeças' },
            { palavra: 'GTA', dica: 'Jogo de mundo aberto com carros e ação' },
            { palavra: 'Among Us', dica: 'Jogo de impostores e tripulantes' },
            { palavra: 'Clash Royale', dica: 'Jogo de cartas e batalhas em tempo real' },
            { palavra: 'Brawl Stars', dica: 'Jogo de batalhas rápidas com personagens carismáticos' },
            { palavra: 'Call of Duty', dica: 'Jogo de guerra com tiroteios intensos' },
            { palavra: 'League of Legends', dica: 'Jogo de estratégia com personagens e rotas' },
            { palavra: 'Just Dance', dica: 'Jogo de dança com músicas populares' },
            { palavra: 'Hollow Knight', dica: 'Jogo de exploração e plataformas com insetos' },
            { palavra: 'Cuphead', dica: 'Jogo difícil com estilo de desenho animado antigo' },
        ],
        [ // Nível difícil
            { palavra: 'Elden Ring', dica: 'Jogo de fantasia com dificuldade elevada' },
            { palavra: 'Persona', dica: 'RPG japonês com vida escolar e monstros' },
            { palavra: 'Undertale', dica: 'Jogo indie onde suas escolhas importam' },
            { palavra: 'Stardew Valley', dica: 'Jogo de fazenda e relacionamentos' },
            { palavra: 'Chrono Trigger', dica: 'RPG clássico com viagens no tempo' },
            { palavra: 'Bioshock', dica: 'Jogo de tiro em cidade submersa' },
            { palavra: 'Dark Souls', dica: 'Jogo conhecido por sua dificuldade extrema' },
            { palavra: 'Celeste', dica: 'Plataforma difícil sobre escalar uma montanha' },
            { palavra: 'The Witcher', dica: 'RPG com bruxo caçador de monstros' },
            { palavra: 'Portal', dica: 'Jogo de quebra-cabeça com armas de portais' },
            { palavra: 'Doom', dica: 'jogo que você enfrenta demônios em Marte com muita velocidade, sangue e heavy metal'}
        ]
    ],
    // filmes
    [
        // Fácil
        [
            { palavra: 'REI LEÃO', dica: 'Filme com um leão chamado Simba' },
            { palavra: 'SONIC', dica: 'O ouriço azul veloz tenta salvar o mundo' },
            { palavra: 'HOTEL TRANSILVÂNIA', dica: 'Hotel para monstros dirigido por Drácula' },
            { palavra: 'FROZEN', dica: 'Filme com a rainha do gelo' },
            { palavra: 'PLANETA DOS MACACOS', dica: 'Humanos enfrentam civilização de macacos inteligentes' },
            { palavra: 'AS MARVELS', dica: 'Heroínas do universo Marvel em missão conjunta' },
            { palavra: 'ZOOTOPIA', dica: 'Cidade dos animais e uma coelha policial investigando' },
            { palavra: 'ESQUADRÃO SUICIDA', dica: 'Vilões são forçados a cumprir missões perigosas' },
            { palavra: 'TOY STORY', dica: 'Filme com brinquedos que ganham vida' },
            { palavra: 'TED', dica: 'Urso de pelúcia ganha vida e vira melhor amigo do protagonista' },
            { palavra: 'LORAX', dica: 'Defensor da floresta enfrenta a destruição ambiental' },
            { palavra: 'UP', dica: 'Velhinho viaja com sua casa voadora e um escoteiro' },
            { palavra: 'OS CROODS', dica: 'Família das cavernas em jornada pela sobrevivência' },
            { palavra: 'PROCURANDO NEMO', dica: 'Peixinho perdido no oceano' },
            { palavra: 'MEU MALVADO FAVORITO', dica: 'Vilão que adota três meninas' },
            { palavra: 'MALÉVOLA', dica: 'A origem da vilã da Bela Adormecida' },
            { palavra: 'A FREIRA', dica: 'Demônio aparece na forma de uma freira' },
            { palavra: 'WALL-E', dica: 'Robô solitário busca salvar a Terra e encontra o amor' },
            { palavra: 'SUPER CÃO', dica: 'Cão com superpoderes salva o dia' },
            { palavra: 'TODO MUNDO EM PÂNICO', dica: 'Paródia de filmes de terror' },
            { palavra: 'OS INCRÍVEIS', dica: 'Família de super-heróis' },
            { palavra: 'SHREK', dica: 'Ogro verde que vive no pântano' },
            { palavra: 'CARROS', dica: 'Filme com veículos falantes' },
            { palavra: 'ENROLADOS', dica: 'Princesa com cabelo mágico e longo' },
            { palavra: 'MADAGASCAR', dica: 'Animais fogem do zoológico e vão parar numa ilha' },
            { palavra: 'O BRINQUEDO ASSASSINO', dica: 'Boneco possuído comete assassinatos' },
            { palavra: 'A HORA DO PESADELO', dica: 'Freddy Krueger ataca suas vítimas nos sonhos' },
            { palavra: 'PIRATAS DO CARIBE', dica: 'Aventuras do Capitão Jack Sparrow' },
            { palavra: 'ANNABELLE', dica: 'Boneca amaldiçoada causa terror' },
            { palavra: 'OS SEGREDOS DOS ANIMAIS', dica: 'Animais falantes fazem festa quando humanos não estão' },
            { palavra: 'SEMPRE AO SEU LADO', dica: 'Cachorro fiel espera por seu dono por anos' },
            { palavra: 'LILO & STITCH', dica: 'Menina havaiana adota um alienígena travesso' },
            { palavra: 'SPACE-JAM', dica: 'Basquete com Pernalonga e estrelas da NBA' },
            { palavra: 'A ERA DO GELO', dica: 'Animais pré-históricos enfrentam desafios juntos' },
            { palavra: 'PINÓQUIO', dica: 'Boneco de madeira sonha em se tornar um menino de verdade' },
            { palavra: 'PEQUENA SEREIA', dica: 'Sereia quer viver na superfície e se apaixona por um humano' },
            { palavra: 'HOMEM-ARANHA', dica: 'Herói que solta teias' },
            { palavra: 'Internet o filme', dica: 'Comédia com youtubers.'},
            { palavra: 'PÂNICO', dica: 'Assassino mascarado aterroriza adolescentes' }
        ],

        // Intermediário
        [
            { palavra: 'O PODEROSO CHEFÃO', dica: 'Clássico sobre a máfia italiana' }, 
            { palavra: 'PERDIDOS EM MARTE', dica: 'Astronauta sobrevive sozinho em Marte' },
            { palavra: 'TROPA DE ELITE', dica: 'Polícia especial do Rio combate o crime' },
            { palavra: 'THUNDERBOLTS', dica: 'Grupo de anti-heróis do universo Marvel' },
            { palavra: 'DEADPOOL', dica: 'Herói sarcástico e imortal enfrenta vilões' },
            { palavra: 'O ILUMINADO', dica: 'Homem enlouquece em hotel isolado e assombra sua família' },
            { palavra: 'A BABA', dica: 'Babá demoníaca em noite assustadora' },
            { palavra: 'GUARDIÕES DA GALÁXIA', dica: 'Grupo de heróis espaciais da Marvel' },
            { palavra: 'LIGA DA JUSTIÇA', dica: 'Grupo de heróis se une para salvar o mundo' },
            { palavra: 'GIGANTES DE AÇO', dica: 'Lutadores de robôs em competições futuristas' },
            { palavra: 'A DAMA E O VAGABUNDO', dica: 'Romance entre dois cães de mundos diferentes' },
            { palavra: 'VALENTE', dica: 'Princesa arqueira enfrenta seu destino na Escócia' },
            { palavra: 'OS SEM FLORESTA', dica: 'Animais descobrem a vida suburbana' },
            { palavra: 'SUPER HERÓI O FILME', dica: 'Paródia dos filmes de super-heróis' },
            { palavra: 'TITANIC', dica: 'Romance trágico a bordo de navio naufragado' },
            { palavra: 'PANTERA NEGRA', dica: 'Herói de Wakanda' },
            { palavra: 'ATÉ QUE A SORTE NOS SEPARE', dica: 'Casal ganha na loteria e perde tudo' },
            { palavra: 'OS VINGADORES', dica: 'Grupo de heróis que luta contra o Thanos' },
            { palavra: 'GENTE GRANDE', dica: 'Grupo de amigos se reencontra com suas famílias' },
            { palavra: 'O MASSACRE DA MOTOSSERRA', dica: 'Família canibal e um assassino com motosserra' },
            { palavra: 'JOGOS MORTAIS', dica: 'Assassino força vítimas a tomarem decisões cruéis' },
            { palavra: 'RUA DO MEDO', dica: 'Cidade amaldiçoada vive uma onda de assassinatos' },
            { palavra: 'MATRIX', dica: 'Realidade virtual e pílula vermelha' },
            { palavra: 'MOANA', dica: 'Aventura de uma jovem navegadora em busca de salvar seu povo' }, 
            { palavra: 'MINHA MÃE É UMA PEÇA', dica: 'Comédia sobre uma mãe irreverente e sua família' },
            { palavra: 'INTERESTELAR', dica: 'Viagem espacial em busca de salvar a humanidade' },
            { palavra: 'BATMAN', dica: 'Herói de capa preta de Gotham' },
            { palavra: 'O HOBBIT', dica: 'Viagem de Bilbo Bolseiro' },
            { palavra: 'IT', dica: 'Palhaço assombra crianças em Derry' },
            { palavra: 'O GRANDE TRUQUE', dica: 'Filme sobre mágicos e rivalidade' }, 
            { palavra: 'CABRAS DA PESTE', dica: 'Dois policiais nordestinos em uma missão maluca' },
            { palavra: 'A CASA DE CERA', dica: 'Grupo encontra museu sinistro com figuras realistas' }, 
            { palavra: 'ELA DANÇA EU DANÇO', dica: 'Jovens se unem através da dança' },         
            { palavra: 'A CLASSE DOS HERÓIS FRACOS', dica: 'Estudantes com superpoderes fora do padrão' },
            { palavra: 'O JOGO DA IMITAÇÃO', dica: 'História de Alan Turing e a quebra de códigos' }
        ],

        // Difícil
        [
            { palavra: 'A ORIGEM', dica: 'Filme sobre sonhos dentro de sonhos' },  
            { palavra: 'MATILDA', dica: 'Garota com poderes especiais e muita inteligência' }, 
            { palavra: 'ESTRELA ALÉM DO TEMPO', dica: 'Cientistas negras da NASA vencem o preconceito' },
            { palavra: 'CLUBE DA LUTA', dica: 'Primeira regra: não fale sobre ele' },
            { palavra: 'O LABIRINTO DO FAUNO', dica: 'Fantasia sombria durante a guerra civil espanhola' },
            { palavra: 'O ÚLTIMO CAÇADOR DE BRUXAS', dica: 'Caçador imortal enfrenta bruxas modernas' },
            { palavra: 'CIDADE DE DEUS', dica: 'Filme brasileiro sobre a favela e o crime' },
            { palavra: 'AMÉLIE POULAIN', dica: 'Jovem francesa que decide ajudar os outros' },
            { palavra: 'FALE COMIGO', dica: 'Ritual com mão embalsamada invoca espíritos' },
            { palavra: 'QUEM QUER SER UM MILIONÁRIO', dica: 'Indiano participa de um quiz na TV' },
            { palavra: 'CLICK', dica: 'Homem encontra controle remoto que manipula o tempo' },
            { palavra: 'O FAROL', dica: 'Filme psicológico com dois homens isolados' },
            { palavra: 'PARASITA', dica: 'Família pobre se infiltra em casa rica' },
            { palavra: 'A CHEGADA', dica: 'Linguista tenta se comunicar com alienígenas' },
            { palavra: 'À Espera de um Milagre', dica: 'Um gigante gentil, poderes de cura e um final de partir o coração no corredor da morte'},
            { palavra: ' A culpa é das estrelas', dica: 'Dois adolescentes com câncer se apaixonam enquanto compartilham livros, sonhos e lágrimas'}
            
        ]
    ]

]

